### ISSUE TITLE
Config.toml vs Edge dictionary for configuration & secrets

### ISSUE THREAD

**Issue by yannh** [fastly/compute-rust-auth#10]
Hello! [This documentation ](https://developer.fastly.com/learning/compute/migrate/) suggests using either a file, or an edge dictionary, to configure Fastly Compute software.  Compute-rust-auth uses the config file approach, with src/config,toml containing the nonce_secret and client_secret.

Another way would be to use an edge dictionary - however [this page](https://docs.fastly.com/en/guides/about-edge-dictionaries) explicitly recommends against it "Personal information, secrets, or sensitive data should not be included in dictionaries or incorporated into VCL.".

An edge dictionary feels like it would allow:
 * to promote the same build artifact between different environments (staging, production)
 * to use the edge dictionary API for regular, automated secret rotation

Also, with config.toml - while it is possible to dynamically edit it at build time, from the template it seems to suggest to store the secret in Git.

Could you expand on the difference between storing secrets within edge dictionaries vs compute binaries? Many thanks!

**Comment by doramatadora** [comment]
Hi @yannh, we will be able to update (and simplify) the bootstrapping here once our edge storage for secrets ([Secret Store](https://developer.fastly.com/learning/concepts/edge-state/dynamic-config#secret-stores)) is out of beta. You can enable this feature now if you want to experiment.

We will be moving the configuration out of the binary and into [Config Store](https://developer.fastly.com/learning/concepts/edge-state/dynamic-config#config-stores), in order to enable the rotation of keys via Fastly's Config Store API, per feature request https://github.com/fastly/compute-rust-auth/issues/18.
